[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Vault Vision"
authors = [{name = "Vault Vision", email = "info@vaultvision.com"}]
dynamic = ["version", "description"]
